Name:           perl-XML-LibXSLT
Version:        1.70
Release:        1.1%{?dist}
Summary:        Interface to the gnome libxslt library
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-LibXSLT/
Source0:        http://www.cpan.org/authors/id/P/PA/PAJAS/XML-LibXSLT-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(XML::LibXML) >= 1.70
BuildRequires:	libxslt-devel >= 1.1.24, gdbm-devel
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(XML::LibXML) >= 1.70
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is an interface to the gnome project's libxslt. This is an
extremely good XSLT engine, highly compliant and also very fast. I have
tests showing this to be more than twice as fast as Sablotron.

%prep
%setup -q -n XML-LibXSLT-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/XML*
%{_mandir}/man3/*

%changelog
* Fri Jan 22 2010 Dennis Gregorovic <dgregor@redhat.com> - 1.70-1.1
- Rebuilt for RHEL 6
Related: rhbz#543948

* Tue Oct 20 2009 Jeff fearn <jfearn@redhat.com> 1.70-1
- Specfile autogenerated by cpanspec 1.77.
